apiVersion: apps/v1
kind: Deployment
metadata:
  name: strongman-tracker
  namespace: default
  labels:
    app: strongman-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strongman-tracker
  template:
    metadata:
      labels:
        app: strongman-tracker
    spec:
      containers:
        - name: strongman-tracker
          image: zackaryclark/strongman-tracker
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: "REACT_APP_HOST_ADDRESS"
              value: "http://localhost:32324/graphql"
