apiVersion: v1
kind: Service
metadata:
  name: strongman-tracker
  namespace: default
spec:
  selector:
    app: strongman-tracker
  ports:
    - protocol: TCP
      port: 80
      nodePort: 32323
  type: NodePort
