apiVersion: apps/v1
kind: Deployment
metadata:
  name: strongman-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strongman-tracker
  template:
    metadata:
      labels:
        app: strongman-tracker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - large
      containers:
        - name: strongman-tracker
          image: zackaryclark/strongman-tracker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "REACT_APP_HOST_ADDRESS"
              value: "https://zackary-clark.duckdns.org/strongman-tracker-api/graphql"
