apiVersion: apps/v1
kind: Deployment
metadata:
  name: strongman-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strongman-tracker
  template:
    metadata:
      labels:
        app: strongman-tracker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - large
      containers:
        - name: strongman-tracker
          image: zackaryclark/strongman-tracker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "API_ADDRESS"
              valueFrom:
                secretKeyRef:
                  key: apiOrigin
                  name: strongman-tracker-secret
            - name: "KC_REALM"
              valueFrom:
                secretKeyRef:
                  key: kcRealm
                  name: strongman-tracker-secret
            - name: "KC_URL"
              valueFrom:
                secretKeyRef:
                  key: kcUrl
                  name: strongman-tracker-secret
            - name: "KC_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key: kcClientId
                  name: strongman-tracker-secret